name: Build RabbitMQ Plugin

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build archive
      uses: ./.github/actions/build-plugin

    - name: Archive build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: rabbitmq_stomp_monitor-v3.12.x.ez
        path: ./plugins/rabbitmq_stomp_monitor-v3.12.x.ez

  tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - uses: erlef/setup-beam@v1
      with:
        otp-version: '26'
        elixir-version: '1.16'

    - name: Run tests
      run: make tests
