name: Release RabbitMQ Plugin

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build archive
      uses: ./.github/actions/build-plugin

    - name: Create a new release
      uses: actions/github-script@v7
      with:
        script: |
          const [repo_owner, repo_name] = process.env.GITHUB_REPOSITORY.split('/')
          const tag_name = process.env.GITHUB_REF.split('/')[2]

          const {data: release} = await github.rest.repos.createRelease({
            owner: repo_owner,
            repo: repo_name,
            tag_name: tag_name,
            generate_release_notes: true
          });

          const fs = require('fs');
          const plugin = fs
              .readdirSync('plugins')
              .find(file => file.match(/rabbitmq_stomp_monitor-.*\.ez/));

          await github.rest.repos.uploadReleaseAsset({
            owner: repo_owner,
            repo: repo_name,
            release_id: release.id,
            name: plugin,
            data: fs.readFileSync(`plugins/${plugin}`)
          });
